language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
script:
  - echo "No tests"
after_success:
  - git clone git://github.com/erseco/GitHubRankingsSpain.git generated
  - make
  - make spain-region
  - git config --global user.email "info@ernesto.es"
  - git config --global user.name "Ernesto Serrano"
  - cd generated
  - git remote
  - git add *
  - git commit -m "New rankings were generated"
  - git push "https://erseco:${ACCESS}@github.com/erseco/GitHubRankingsSpain.git" master > /dev/null 2>&1
