name: Build

on:
  push:
  schedule:
    - cron:  '* 7 * * 1'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1
    - name: Install requirements
      run: |
        pip3 install setuptools wheel
        pip3 install -r requirements.txt
    - name: Generate ranking
      run: |
        git clone git://github.com/erseco/GitHubRankingsSpain.git generated

        make multi
        make spain-region

        git config --global user.email "info@ernesto.es"
        git config --global user.name "Ernesto Serrano"
        cd generated
        git remote
        git add *
        git commit -m "New rankings were generated"
        git push "https://erseco:${ACCESS}@github.com/erseco/GitHubRankingsSpain.git" master > /dev/null 2>&1

      env:
        ACCESS: ${{ secrets.GITHUB_TOKEN }}